apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 9090 # Service port
    targetPort: 9090 # Container port
  type: ClusterIP
