apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 7070 # Service port
    targetPort: 7070 # Container port
  type: ClusterIP
